### ISSUE TITLE
Support for 64-bit platforms

### ISSUE THREAD

**Issue by WAUthethird** [thargor6/mb3d#9]
Hey there - one of the most important things this project needs if it is to move forward is support for 64-bit platforms.

So, say that I successfully compiled with Lazarus - what then? Would it be a 64-bit application? Or is there code that needs to be ported over?

**Comment by bezo97** [comment]
There's a lot of assembly code in the project with 32-bit instructions. You'd need to rewrite them to utilize the larger address space. Also afaik there are a few instructions and registers not available in 64-bit.

**Comment by thargor6** [comment]
Hi, this issue has been discussed a lot of times: to make this app 64 bit, you will have to understand and rewrite large parts of the core, including most of the formulas. Most of the formulas are not documented, there is only the 32bit ASM code.
 
So, this will probably not happen because it is a very large and tedious task.
And, there are alternatives, for example Vectron.

Cheers!
